source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'
inhibit_all_warnings!

project 'runTimeTest.xcodeproj'

target :runTimeTest do
    pod 'IQKeyboardManager'
    pod 'SDWebImage'
    pod 'BLLazyImageLoad'
    pod "AFNetworking"
end
